tasks:
  - name: Setup and Run App
    before: |
      echo "Updating system packages and installing Chrome dependencies..."
      sudo apt-get update && sudo apt-get install -y libnss3 libatk-bridge2.0-0 libcups2 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2 libasound2
      
      echo "Installing Python dependencies..."
      pip install -r laser_calculator_app/requirements.txt
      
      echo "Installing Chrome for PDF exports..."
      plotly_get_chrome
    command: |
      echo "Navigating to app directory and starting Streamlit..."
      cd laser_calculator_app
      streamlit run app.py